databases:
  - name: one_small_thing_be
    databaseName: one_small_thing_be
    user: one_small_thing_be_user

services:
  - type: web
    name: one-small-thing
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: postgres://one_small_thing_be_user:h7P8FssAkUYDB7p2tzKUZQ0JJMhJGAmI@dpg-cc4k9l98f8til1qqso2g-a/one_small_thing_be
        fromDatabase:
          name: One_Small_Thing_BE
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
